PORT = "PORT"

# Request statuses
TYPE = "TYPE"

PING = "PING"
INIT = "INIT"
VOTE = "VOTE"
SHUTDOWN = "SHUTDOWN"
CONFIG = "CONFIG"
MASTERSELECT = "MASTERSELECT"
UPLOADIMAGE = "UPLOADIMAGE"
PREDICT = "PREDICT"

PONG = "PONG"

STATUS = "STATUS"
FAILURE = "FAILURE"
SUCCESS = "SUCCESS"

# Config
ISMASTER = "isMaster"
SCANSET = "scanSet"

CONFIG = "CONFIG"
PEERS = "peers"

# Voting
MYVOTE = "MYVOTE"
NEWMASTER = "NEWMASTER"

# Predict
FILENAME = "FILENAME"
PREDICTION = "PREDICTION"